"""Initial relational schema

Revision ID: 0001
Revises:
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("type", sa.String(length=100), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("run_id", sa.String(length=32), nullable=True),
        sa.Column("project_id", sa.String(length=32), nullable=True),
        sa.Column("execution_id", sa.String(length=32), nullable=True),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_events_execution_id"), ["execution_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_events_run_id"), ["run_id"], unique=False)

    op.create_table(
        "github_apps",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("app_id", sa.String(length=100), nullable=False),
        sa.Column("slug", sa.String(length=200), nullable=False),
        sa.Column("credential_ref", sa.String(length=200), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "github_installations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("account", sa.String(length=200), nullable=False),
        sa.Column("permissions", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "projects",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("task_log", sa.Text(), nullable=False),
        sa.Column("next_run_feedback", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("default_model", sa.String(length=200), nullable=False),
        sa.Column("default_reasoning_effort", sa.String(length=24), nullable=False),
        sa.Column("storage_metadata", sa.JSON(), nullable=False),
        sa.Column("thread_id", sa.String(length=200), nullable=True),
        sa.Column("last_run_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "schedules",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("cron", sa.String(length=200), nullable=False),
        sa.Column("timezone", sa.String(length=100), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("run_template", sa.JSON(), nullable=False),
        sa.Column("next_run_at", sa.DateTime(), nullable=False),
        sa.Column("last_run_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("schedules", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_schedules_next_run_at"), ["next_run_at"], unique=False)

    op.create_table(
        "settings",
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("value", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "project_github_integrations",
        sa.Column("project_id", sa.String(length=32), nullable=False),
        sa.Column("installation_id", sa.Integer(), nullable=False),
        sa.Column("repository_id", sa.Integer(), nullable=False),
        sa.Column("repository_name", sa.String(length=300), nullable=False),
        sa.Column("permissions", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("project_id"),
    )
    op.create_table(
        "runs",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.Column("parallel", sa.Boolean(), nullable=False),
        sa.Column("stop_conditions", sa.JSON(), nullable=False),
        sa.Column("cancel_requested", sa.Boolean(), nullable=False),
        sa.Column("schedule_id", sa.String(length=32), nullable=True),
        sa.Column("scheduled_for", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["schedule_id"], ["schedules.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("runs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_runs_status"), ["status"], unique=False)
        batch_op.create_index(
            "uq_schedule_occurrence", ["schedule_id", "scheduled_for"], unique=True
        )

    op.create_table(
        "secret_entries",
        sa.Column("project_id", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("credential_ref", sa.String(length=200), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("project_id", "name"),
    )
    op.create_table(
        "project_executions",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("run_id", sa.String(length=32), nullable=False),
        sa.Column("project_id", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("model", sa.String(length=200), nullable=False),
        sa.Column("reasoning_effort", sa.String(length=24), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.Column("thread_id", sa.String(length=200), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("vm_metadata", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["run_id"], ["runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("project_executions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_project_executions_project_id"), ["project_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_project_executions_run_id"), ["run_id"], unique=False)
        batch_op.create_index(
            "uq_project_active",
            ["project_id"],
            unique=True,
            sqlite_where=sa.text(
                "status IN ('queued','preparing','starting_vm','running','stopping')"
            ),
        )

    op.create_table(
        "run_reports",
        sa.Column("execution_id", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("content", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(["execution_id"], ["project_executions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("execution_id"),
    )
    op.create_table(
        "usage_snapshots",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("execution_id", sa.String(length=32), nullable=True),
        sa.Column("observed_at", sa.DateTime(), nullable=False),
        sa.Column("windows", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(["execution_id"], ["project_executions.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("usage_snapshots", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_usage_snapshots_execution_id"), ["execution_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_usage_snapshots_observed_at"), ["observed_at"], unique=False
        )

    op.create_table(
        "automations",
        sa.Column("id", sa.String(32), primary_key=True),
        sa.Column("name", sa.String(200), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("trigger", sa.JSON(), nullable=False),
        sa.Column("mode", sa.String(24), nullable=False),
        sa.Column("run_template", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("last_checked_at", sa.DateTime(), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
    )
    op.create_table(
        "automation_occurrences",
        sa.Column("id", sa.String(32), primary_key=True),
        sa.Column("automation_id", sa.String(32), nullable=True),
        sa.Column("automation_name", sa.String(200), nullable=False),
        sa.Column("limit_id", sa.String(200), nullable=False),
        sa.Column("window_minutes", sa.Integer(), nullable=False),
        sa.Column("resets_at", sa.DateTime(), nullable=False),
        sa.Column("matched_window", sa.JSON(), nullable=False),
        sa.Column("run_template", sa.JSON(), nullable=False),
        sa.Column("mode", sa.String(24), nullable=False),
        sa.Column("status", sa.String(24), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("notified_at", sa.DateTime(), nullable=True),
        sa.Column("delivery_error", sa.Text(), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("run_id", sa.String(32), nullable=True),
        sa.ForeignKeyConstraint(["automation_id"], ["automations.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["run_id"], ["runs.id"], ondelete="SET NULL"),
    )
    op.create_index(
        "uq_automation_occurrence",
        "automation_occurrences",
        ["automation_id", "limit_id", "window_minutes", "resets_at"],
        unique=True,
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_table("automation_occurrences")
    op.drop_table("automations")
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("usage_snapshots", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_usage_snapshots_observed_at"))
        batch_op.drop_index(batch_op.f("ix_usage_snapshots_execution_id"))

    op.drop_table("usage_snapshots")
    op.drop_table("run_reports")
    with op.batch_alter_table("project_executions", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_project_active",
            sqlite_where=sa.text(
                "status IN ('queued','preparing','starting_vm','running','stopping')"
            ),
        )
        batch_op.drop_index(batch_op.f("ix_project_executions_run_id"))
        batch_op.drop_index(batch_op.f("ix_project_executions_project_id"))

    op.drop_table("project_executions")
    op.drop_table("secret_entries")
    with op.batch_alter_table("runs", schema=None) as batch_op:
        batch_op.drop_index("uq_schedule_occurrence")
        batch_op.drop_index(batch_op.f("ix_runs_status"))

    op.drop_table("runs")
    op.drop_table("project_github_integrations")
    op.drop_table("settings")
    with op.batch_alter_table("schedules", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_schedules_next_run_at"))

    op.drop_table("schedules")
    op.drop_table("projects")
    op.drop_table("github_installations")
    op.drop_table("github_apps")
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_events_run_id"))
        batch_op.drop_index(batch_op.f("ix_events_execution_id"))

    op.drop_table("events")
    # ### end Alembic commands ###
